# Preprocessing in Python

Let's look at doing some preprocessing using pandas and scikit-learn in Python.

In [ ]:
# First of all, we need to install the packages we want to use: numpy, pandas and scikit-learn.  - we do not need this step in Google Colab, but you do need it in Anaconda environment.
# !python3 -m pip install numpy pandas scikit-learn

## Why Pandas?
- One of the most popular library that data scientists use, designed for working with heterogenous tabular data vs NumPy homogenous array data
- Labeled axes to avoid misalignment of data, e.g. when merge two tables, some rows may be different
- Missing values or special values may need to be removed or replaced

Now, let's import them:

In [1]:
import numpy as np
import pandas as pd
import sklearn as sk  # note that the module name is not necessarily the same as the package name

## Opening the data file
Now we need to open the abalone file. We do this using pandas. You can search for these in the pandas help yourself, but the functions of interest are:
- `pandas.read_csv` and `pandas.to_csv` to read and write CSV files.
- `pandas.read_excel` and `pandas.to_excel` to read and write MS Excel files

We're going to open the iris file. Note: you will need to edit the code to ensure that it points to where you have uploaded the `iris-u2.csv` file.

In [5]:
iris_path = "iris-u2.csv" # file uploaded to Colab notebook's hosted server.
# iris_path =   "C:/Users/119489/OneDrive - UTS/teaching/UTS/2023 Spring/32130/content/w2/iris-u2.csv"
# Since a Colab notebook is hosted on Google’s cloud servers, there’s no direct access to files on your local drive
# (unlike a notebook hosted on your machine) or any other environment by default.

adata = pd.read_csv(iris_path)

## Taking a quick look at the data
You can of course just display the variable or use `.head()` or `.tail()` to see the top or bottom of the dataset.

In [10]:
# adata
adata.head() # be careful with indentation
# adata.tail()

   Row  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0    1           5.1          3.5           1.4          0.2  setosa
1    2           4.9          3.0           1.4          0.2  setosa
2    3           4.7          3.2           1.3          0.2  setosa
3    4           4.6          3.1           1.5          0.2  setosa
4    5           5.0          3.6           1.4          0.2  setosa

You can see the column names with `.columns` and the row indices with `.index`.

In [15]:
#adata.index
#adata.columns
#type(adata)

Index(['Row', 'Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

## Accessing data
### Accessing columns
To access columns use the `[colname]` or the `.`. This returns a Series.
For example, `adata['Height']` or `adata.Height`. In contrast, `adata[['Height']]` returns a DataFrame.

In [21]:
#adata['Sepal.Length']
#adata.Sepal.Length # what is happening here? why? - various methods to access

adata[['Sepal.Length']] # put the first line of this cell into a different cell, and check the differences of the outputs.

     Sepal.Length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

### Accessing a subset of rows
To access a subset of rows, you can do the following: `adata[0:3]` selects rows 0, 1 and 2.

In [22]:
adata[0:2]

   Row  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0    1           5.1          3.5           1.4          0.2  setosa
1    2           4.9          3.0           1.4          0.2  setosa

### loc and iloc
A more straightforward and more powerful way to access parts of the DataFrame is with `loc` which takes a label or list of labels and `iloc` which takes an index or list of indices. Note: you're indexing not calling a function, so use `[]` not `()`.

In [24]:
# adata.loc[[0, 2, 3], ['Sepal.Length', 'Species']]
# adata.loc[0:3, ['Sepal.Length', 'Species']]
adata.loc[3:5, ['Sepal.Length', 'Species']]
#adata.loc[:, ['Sepal.Length', 'Species']]

   Sepal.Length Species
3           4.6  setosa
4           5.0  setosa
5           5.4  setosa

In [27]:
# adata.iloc[:]
# adata.iloc[:, 1:4]
adata.iloc[3:6, [1,5]] # pay attention to the ending number -

   Sepal.Length Species
3           4.6  setosa
4           5.0  setosa
5           5.4  setosa

In [31]:
adata_out = adata.drop(['Row'],axis=1) #from the column labels (axis 0)
# adata.drop(['Row'],axis=1, inplace=True)

# many other data-preprocessing methods can be found here:
# https://www.geeksforgeeks.org/working-with-missing-data-in-pandas/
# https://pandas.pydata.org/docs/reference/frame.html

In [32]:
adata_out #

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [34]:
adata_out.to_csv('iris-u2-out-python.csv')

Remember to download the output file 'iris-u2-out.csv' to your local disk.
Also remember to download this .ipynb to your local disk for future use.